### ISSUE TITLE
Timeseries data info & unit

### ISSUE THREAD

**Issue by nsankar** [gregvanhoudt/AITIA-PM#1]
@gregvanhoudt  The AITIA-PM paper is an interesting one to read. Thanks for developing the package.

I have a couple of questions. 

1. The CaseLog_Experiment_1.csv data contains numerical values ranging from 0 to 11478.370938333339 for various cases. What does this represent and what is its unit? Is it the time of occurrence of a  given case event like in milliseconds?

2.  The other data file CoSeLoG project.csv contains timestamps of case events. Can we directly use this data file as it is for processing in main.py **or** does it require any changes in time unit conversion?   

Thanks in advance.

**Comment by gregvanhoudt** [comment]
Hi @nsankar 


Thank you for your interest!

1. The dataset contains three (unlabeled) columns: the case, the observation and the time unit. In this case, the time unit is expressed in hours, starting from the first event. For example, the 5th event took place 0.18948194444179534 hours after the first.
2. This csv is the original event log (converted from .xes to .csv format). In the current code base, the preprocessing to the case | observation | time unit format is manual work. However, I am working on adding this preprocessing to the algorithm so that you can indeed work directly on the event log.

I hope this answers your questions.


Kind regards
Greg

**Comment by nsankar** [comment]
@gregvanhoudt . Got it. Thanks. Yes. An inbuilt preprocessing will help.
